<?php

namespace IServ\NachschreibarbeitenBundle;

/**
 * Entity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Entity extends \Doctrine\ORM\EntityRepository
{
}
